<input type="checkbox" />
<nav>
  <ul>
    <li>
      <a href="./"> <img src="images/main-icon.png" alt="Main home page" />Home</a>
    </li>
    <li>
      <a href="xosd">
        <img src="images/xosd-icon.png" alt="XOSD - X11 On Screen Display library" />XOSD</a
      >
    </li>
    <li>
      <a href="bach-sleepout">
        <img src="images/bach-icon.png" alt="My Bach/Sleepout plans & info" />Bach/Sleepout</a
      >
    </li>
    <li>
      <a href="r36s">
        <img src="images/r36s-icon.png" alt="R36S handheld game console Linux info" />R36S
        Hacking</a
      >
    </li>
    <li>
      <a href="mango-pi-mini">
        <img src="images/mango-pi-mini-icon.png" alt="MangoPi MQ Dual mini Linux info" />MangoPI MQ
        Boot Speed</a
      >
    </li>
  </ul>
</nav>
